#!/usr/bin/python3

import requests

bot_token = "INSERT YOUR TOKEN"
chat_id = "INSERT CHAT ID"
check_url = "INSERT URL"

res = requests.get(check_url)

if res.status_code != requests.codes.ok:

    send_message_url = f'https://api.telegram.org/bot{bot_token}/sendMessage'
    message_text = f"Alarm! {check_url} doesn't respond!"
    payload = {
        'chat_id': chat_id,
        'text': message_text
    }
    response = requests.post(send_message_url, data=payload)
    message_text
